version: 2
updates:
  - package-ecosystem: pip
    directory: /packages/backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      backend-deps:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /packages/ml-models
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /packages/pro-demo-ingester
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /packages/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
