export { api, ApiError, API_BASE, USE_MOCKS } from '@/lib/api-client'
export * as authApi from './auth'
export * as demosApi from './demos'
export * as matchesApi from './matches'
export * as playersApi from './players'
export * as proApi from './pro'
export * as billingApi from './billing'
export * as scoutApi from './scout'
export * as trainingApi from './training'
export * as predictionApi from './prediction'
