[mypy]
python_version = 3.12
strict = true
plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[mypy-jose.*]
ignore_missing_imports = True

[mypy-argon2.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True
